version: "3.9"

x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  env_file: .env
  user: "${AIRFLOW_UID}:0"
  environment:
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    GOOGLE_APPLICATION_CREDENTIALS: /usr/local/airflow/gcloud_credentials.json
  volumes:
    - .:/usr/local/airflow
    - ./gcloud_credentials.json:/usr/local/airflow/gcloud_credentials.json:ro

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5

  webserver:
    <<: *airflow-common
    ports:
      - "8080:8080"
    command: webserver
    depends_on:
      - postgres

  scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      - postgres

volumes:
  postgres-db-volume:

