name: 'battery_project'
version: '1.0'
config-version: 2

profile: battery_profile

models:
  battery_project:
    +materialized: view  # default for all models
    battery_cleaned:
      +materialized: table
    battery_features:
      +materialized: table

