iname: 'battery_project'
version: '1.0'
config-version: 2

profile: 'default'

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  battery_project:
    materialized: table

