version: 2

models:
  - name: battery_ts_cleaned
    description: "Cleaned battery data with standard formatting and filters applied"
    columns:
      - name: streamed_at
        description: "Timestamp of data stream"
      - name: capacity
        description: "Battery capacity after filtering out outliers"

